### ISSUE TITLE
oauthproxy.go:535: 172.17.0.1:42982 Cookie "_oauth2_proxy1" not present

### ISSUE THREAD

**Issue by rzvn2600** [bitly/oauth2_proxy#485] opened 2017-10-25 07:54 UTC
Hello all,

I am facing an issue when using oauth2 + nginx to login to a kibana instance through my google account.

I have the following configuration for oauth:
`./oauth2_proxy \
 --email-domain="*" \
 --upstream="http://localhost:8080/" \
 --approval-prompt="auto" \
 --redirect-url="http://localhost:4180/oauth2/callback" \
 --http-address="http://:4180" \
 --cookie-secret=secretsecret \
 --cookie-name="_oauth2_proxy1" \
 --cookie-secure=false \
 --provider=google \
 --client-id="***" \
 --client-secret="***"`

The nginx configuration is the following: 
`server {
            listen 8080;
            server_name localhost;

            location / {

                # The location of our Kibana server (this is default)

                proxy_pass http://localhost:5601/;

                # Send a Basic auth header to Kibana on every request to get past the log - in UI.
                # "bmdpbng6c2VjcmV0cGFzc3dvcmQ="is a base64 encoded string of my service account 's credentials "nginx:secretpassword"

                proxy_set_header Authorization "Basic bmdpbng6c2VjcmV0cGFzc3dvcmQ=";

                # Also submit the 'es-security-runas-user'header on every request with a value of X - Forwarded - User sent from the downstream oauth2_proxy.
                # X-Forwarded-User would be 'user1' if the Google account was user1 @elastic.co

                proxy_set_header es-security-runas-user http_x_forwarded_user;

                # Simple rewrite to get us back to oauth2_proxy 's login page if someone uses Kibana's Logout button.

                rewrite /login http://localhost:4180/oauth2/sign_in redirect;
            }
        }
}`

I get authenticated with my google account but the oauth_proxy is loosing the token as in the following logs:
```172.17.0.1 - - [25/Oct/2017:07:35:26 +0000] localhost:4180 GET - "/oauth2/start?rd=%2Foauth2%2Fsign_in%3Fnext%3D%252F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 302 354 0.000
172.17.0.1 - - [25/Oct/2017:07:35:26 +0000] localhost:4180 GET - "/oauth2/start?rd=%2Foauth2%2Fsign_in%3Fnext%3D%252F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 302 354 0.000
172.17.0.1 - - [25/Oct/2017:07:35:26 +0000] localhost:4180 GET - "/oauth2/start?rd=%2Foauth2%2Fsign_in%3Fnext%3D%252F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 302 354 0.000
172.17.0.1 - - [25/Oct/2017:07:35:26 +0000] localhost:4180 GET - "/oauth2/start?rd=%2Foauth2%2Fsign_in%3Fnext%3D%252F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 302 354 0.000
2017/10/25 07:35:27 oauthproxy.go:490: 172.17.0.1:42982 authentication complete Session{sierra.tango.bravo@gmail.com token:true expires:2017-10-25 08:35:27 +0000 UTC}
172.17.0.1 - - [25/Oct/2017:07:35:26 +0000] localhost:4180 GET - "/oauth2/callback?state=/oauth2/sign_in?next%3D%252F&code=4/hc81d9a3l4M8PjwxOgC39bdX8Lh7FRIQHhFqebnfHYc" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 302 47 0.197
172.17.0.1 - - [25/Oct/2017:07:35:27 +0000] localhost:4180 GET - "/oauth2/sign_in?next=%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 200 2499 0.000
2017/10/25 07:35:27 oauthproxy.go:535: 172.17.0.1:42982 Cookie "_oauth2_proxy1" not present
172.17.0.1 - - [25/Oct/2017:07:35:27 +0000] localhost:4180 GET - "/favicon.ico" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" 403 2487 0.001
```

I tried to change my email domain, from elastic.co to gmail.com to "*" but still the "_oauth2_proxy1" cookie is not present.

I would appreciate any input on this.
Thanks

**Comment by ploxiln** [comment] 2017-10-26 05:39
The `/oauth2/start` request somehow has an "rd" query param value of "/oauth2/sign_in?next=/" and thus after the oauth callback that's the next request. The `/oauth2/sign_in` handler intentionally clears the cookie so you can sign-in again. The problem is at the start - you need to figure out why "rd=%2Foauth2%2Fsign_in%3Fnext%3D%252F" was passed in the url.

**Comment by jehiah** [comment] 2017-10-26 13:03
Closing in favor of #456

**Closed** 2017-10-26 13:03 UTC
Labels: question
